{% set name = "xgboost" %}
{% set version = "2.1.1" %}

# note: r-xgboost is built from https://github.com/AnacondaRecipes/aggregateR/tree/R-4.3.1/r-xgboost-feedstock

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/dmlc/xgboost/releases/download/v{{ version }}/xgboost-{{ version }}.tar.gz
  sha256: a47ca87f3345d2a866cd7ec40933564aa2b7250592d0e9bf613951630fc1fa6f

build:
  skip: True  # [py<38]
  number: 0

outputs:
  - name: libxgboost
    script: build-libxgboost.sh  # [not win]
    script: build-libxgboost.bat  # [win]
    build:
      skip: True  # [py<38]
      missing_dso_whitelist:
        - $RPATH/ld64.so.1  # [s390x]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja-base
        - llvm-openmp  # [osx]
      host:
        - llvm-openmp  # [osx]
        - nccl         # [linux and x86_64]
      run:
        - llvm-openmp  # [osx]
        - _openmp_mutex  # [linux]
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    test:
      commands:
        - test -f ${PREFIX}/lib/libxgboost${SHLIB_EXT}       # [unix]
        - if not exist %LIBRARY_BIN%\\xgboost.dll exit 1     # [win]

  - name: _py-xgboost-mutex
    version: 2.0
    build:
      skip: True  # [py<38]
      string: cpu_0
      number: 0
    test:
      commands:
        - echo "Hello py boost!"

  - name: py-xgboost
    script: build-py-xgboost.sh  # [not win]
    script: build-py-xgboost.bat  # [win]
    build:
      skip: True  # [py<38]
    requirements:
      host:
        - python
        - pip
        - hatchling >=1.12.1
        - {{ pin_subpackage('libxgboost', exact=True) }}
      run:
        - {{ pin_subpackage('libxgboost', exact=True) }}
        - {{ pin_subpackage('_py-xgboost-mutex', exact=True) }}
        - python
        - numpy
        - scipy
          # mkl variant pulls in intel-openmp which conflicts with llvm-openmp. i.e. force to use openblas variant of numpy, scipy, etc.
        - blas=*=openblas  # [osx and x86_64]
    test:
      requires:
        - pip
        - scikit-learn
      script: test-py-xgboost.py        # [not s390x]
      imports:
        - xgboost
      commands:
        - pip check

  - name: py-xgboost-cpu
    build:
      skip: True  # [py<38]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('py-xgboost', exact=True) }}

  - name: xgboost
    build:
      skip: True  # [py<38]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('py-xgboost', exact=True) }}

about:
  home: https://github.com/dmlc/xgboost
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    Scalable, Portable and Distributed Gradient Boosting (GBDT, GBRT or GBM) Library, for
    Python, R, Java, Scala, C++ and more. Runs on single machine, Hadoop, Spark, Flink
    and DataFlow
  description: |
    XGBoost is an optimized distributed gradient boosting library designed to be highly efficient,
    flexible and portable. It implements machine learning algorithms under the Gradient Boosting
    framework. XGBoost provides a parallel tree boosting (also known as GBDT, GBM) that solve many
    data science problems in a fast and accurate way. The same code runs on major distributed
    environment (Hadoop, SGE, MPI) and can solve problems beyond billions of examples.
  doc_url: https://xgboost.readthedocs.io/
  dev_url: https://github.com/dmlc/xgboost/

extra:
  feedstock-name: xgboost
  recipe-maintainers:
    - aldanor
    - fhoehle
    - jakirkham
    - ksangeek
    - xhochy
