{% set name = "xgboost" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/dmlc/xgboost
  git_tag: v{{ version }}
  patches:
    # xgboost patches
    - 0001-conda-Unbundle-libxgboost.-so-dll.patch
    - 0002-Fix-R-package-PKGROOT.patch
    - 0003-Fix-R-package-mingw-w64-compiler-flags-remove-m64.patch
    # dmlc-core patches
    - 0001-Do-not-define-fopen64-as-std-fopen-on-32-bit-mingw-w.patch

requirements:
  build:
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - llvm-openmp >=4.0.1    # [osx]
    - m2w64-toolchain        # [win]
    - git                    # [not win]
    - m2-git                 # [win]
    - make                   # [not win]
    - m2-make                # [win]
  host:
    - llvm-openmp >=4.0.1    # [osx]

outputs:
  - name: libxgboost
    script: install-libxgboost.sh
    requirements:
      run:
        - m2w64-gcc-libs     # [win]

  - name: py-xgboost
    script: install-py-xgboost.sh
    requirements:
      host:
        - {{ pin_subpackage('libxgboost', exact=True) }}
        - python
        - numpy
        - scipy
        - scikit-learn
    test:
      script: test-py-xgboost.py

  - name: r-xgboost
    requirements:
      - {{ pin_subpackage('libxgboost', exact=True) }}
      - r-base
      - r-matrix
      - r-data.table
      - r-magrittr
      - r-stringi
    script: install-r-xgboost.sh
    test:
      script: test-r-xgboost.r
