travis:
  secure:
    BINSTAR_TOKEN: fVbaCVZ4QlbV7NXIJzUL5GMhjX17es/O1C72vt2oRjxRTlihZL6PzKZe83/Npi5sTo7wFGymrulqRmKMkJ2bEYpbtRsdJTAJzP+j4vX57WjN+u+pFv7bDhtJ82A4fJEaUA7Ar3R0uJgaRkZOq8vVLTt8FhOD6u4vjZdcc2zhvgFadTZIBoXjSQNABA3xdGEGYJLhRxwYVjDNhFiXXKaQoFZI3ORgwBmJGsP4EqgVf/SVR46R87FE80xp7mzlhVi6zzjt5kXG+7ZRyMI/DRp7RyR91XJnzzSEYksppVnUlSDltULPQCpvtQHH1uwNFrMXMSSmhvw3EjFnC4GHR3utKlH9F7ixES7HJZF06AyHJx4qpeFQ4LOYK0kCX3Y+GoXTH6O6xkcpAWvbBb0A1cdsa3Rvb5HBpOHjdVgbdrrlrhF5pyzRy63kq+iZ79//KqWT920VbpxJkfuob1lkSPaM4uSpzgAQ/cb4/mmqelOXFRzeHZqk+DAqIZMYdevGlHeM9pZSUgMfWCr7BAR3I254sDXmTtCA9Ke4t/xAr+IzWjYdtdmRG8o0DD5eCLoG64doGLZhZttavA+dQf1WvDCIOwx5gBonxTYIgQs6xFx1wBR4PFf6l1myzWtaQWnqGWogGy8xBySOx7cVFiv8Fy9prkgpNndyp5skgcIyblhPleQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
