travis:
  secure:
    BINSTAR_TOKEN: g7PlB9oUDuWjbdtMAEFXXwCdwCr2HxiNSKUBhScK/Ie6jafYWDw2SUSLUIkSp/0sz1FPRPEVvRPgq8vqZwx0Mp6ApRnbY0Lts1OSe3JTysSoMYiR6E2lkOOE6MqowCZnz/jo4W/DHbVP6tBv5tXml73JAWzVkzC26bz4HFDJ4dSsAhL7Y6PvP7jf/8KIdNzTH6uYu9cBVMZuQdykzylDfczZyoSdx8kwQZI0gLXPb0lJ0iwNalHkT4MFlYodDUpMO8Jpci4naW5V7rhk51/Y2F2jmsSG/mN80t5kPTmQlr3atuTZSLhRdBj0JzZC423bKr3yQDRbGFknMBHMIVnVj0ZcX2hiShF3VfwPL0RLJ0vKvtnvAXbLhbx2bB1xwAZubljfUgNxzJrFlCARtSgNqisu6OVLeTGcslTFC91PYJAWEv1TYf67EqA2zKK4vbRk1imaBVhkmp6bA7hxIB/GcU61kJudzigQ+QnWdkS6o9iwnrt5oR91uaSSbAhGJMZR6JGyBrlYimnn9qUEamB8NholgrMkloqeUdlSzcqbWbpgJAriaHZlHa8RZiPFqUsqHlpO30tcA9W8PcJrbYwIoQP5AmirdY2NDacRwi8rEgGERYsuru2jkkufBCgxBdzxqVyy267+5VUiS29Jes8Vv6bgdHpJ7F3/JiSpp190ltY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
